import Link from "next/link"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header >
          <nav className="inline-grid grid-cols-3 gap-4 w-full">

<Link className="bg-yellow-400" href={"/"}>
Home
</Link>
      
<Link href="/about">
  About Us
</Link>

          </nav>

        </header>
        {children}
        <footer>This is footer of the page</footer>
        </body>
    </html>
  )
}
