import NavBar from "@/components/navbar";
import "./globals.css";
import Link from "next/link";
import { NavigatingProgrammatically } from "@/components/NavigatingProgamatically";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="isolate bg-white px-6 py-24 sm:py-32 lg:px-8">
        <header>
          <nav
            style={{
              display: "flex",
              justifyContent: "flex-start",
              gap: "2rem",
            }}
          >
            <Link className="text-blue-500 hover:text-blue-700" href={"/"}>Home</Link>


            <Link className="text-blue-500 hover:text-blue-700" href="/blog">Blog</Link>

            <Link className="text-blue-500 hover:text-blue-700" href="/products">View Products</Link>

            <Link className="text-blue-500 hover:text-blue-700" href="/docs">Docs</Link>

            <Link className="text-blue-500 hover:text-blue-700" href={"/profile"}>Profile</Link>
            <Link className="text-blue-500 hover:text-blue-700" href={"/news/123?lan=English"}>News</Link>


          </nav>

        </header>
        <hr />
<h2>Active Links</h2>
<NavBar/>
<hr />

        {children}
        <hr />
<NavigatingProgrammatically/>
        <footer>This is footer of the page</footer>
      </body>
    </html>
  );
}
